/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_Measure.h"
#include "RPI_UART.h"
#include "RPI_TX_aliases.h"
#include "RPI_TX.h"
#include "Color_PWM.h"
#include "Color_Counter.h"
#include "isr_Color.h"
#include "RPI_RX_aliases.h"
#include "RPI_RX.h"
#include "Color_Pin_Freq_Select_aliases.h"
#include "Color_Pin_Freq_Select.h"
#include "Weight_Ref_Pin_aliases.h"
#include "Weight_Ref_Pin.h"
#include "Actuator_Pin_IN1_aliases.h"
#include "Actuator_Pin_IN1.h"
#include "Proximity_Pin_Measure_aliases.h"
#include "Proximity_Pin_Measure.h"
#include "Proximity_Pin_Actuator_aliases.h"
#include "Proximity_Pin_Actuator.h"
#include "isr_Actuator.h"
#include "Weight_ADC.h"
#include "PWM_Clock.h"
#include "Counter_Clock.h"
#include "Color_Reset.h"
#include "Color_Pin_Freq_aliases.h"
#include "Color_Pin_Freq.h"
#include "Color_Pin_Color_Select_aliases.h"
#include "Color_Pin_Color_Select.h"
#include "Color_Pin_LED_aliases.h"
#include "Color_Pin_LED.h"
#include "Motor_PWM.h"
#include "Clock_1.h"
#include "Motor_Pin_PWM_aliases.h"
#include "Motor_Pin_PWM.h"
#include "isr_rx.h"
#include "Actuator_PWM.h"
#include "Actuator_Pin_IN2_aliases.h"
#include "Actuator_Pin_IN2.h"
#include "Clock_2.h"
#include "Actuator_Dir.h"
#include "RPI_UART_IntClock.h"
#include "Weight_ADC_IRQ.h"
#include "Weight_ADC_theACLK.h"
#include "Weight_ADC_ExtVref_aliases.h"
#include "Weight_ADC_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

